[package]
name = "reisplanner-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
rbs = "4.5.18"
rbatis = "4.5.29"
rbdc-sqlite = "4.5.5"
anyhow = "1.0.86"
tracing = "0.1.40"
serde = { version = "1.0.203", features = ["derive"] }
